//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connector.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("youruser@yourdomain.com")]
        public string UserDevTest
        {
            get
            {
                return ((string)(this["UserDevTest"]));
            }
            set
            {
                this["UserDevTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yourPassword")]
        public string UserDevPassword
        {
            get
            {
                return ((string)(this["UserDevPassword"]));
            }
            set
            {
                this["UserDevPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://yourenvironment.crm4.dynamics.com/")]
        public string URLDev
        {
            get
            {
                return ((string)(this["URLDev"]));
            }
            set
            {
                this["URLDev"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("youruser@yourdomain.com")]
        public string UserPreTest
        {
            get
            {
                return ((string)(this["UserPreTest"]));
            }
            set
            {
                this["UserPreTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yourPassword")]
        public string UserPrePassword
        {
            get
            {
                return ((string)(this["UserPrePassword"]));
            }
            set
            {
                this["UserPrePassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://yourenvironment.crm4.dynamics.com/")]
        public string URLPre
        {
            get
            {
                return ((string)(this["URLPre"]));
            }
            set
            {
                this["URLPre"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("youruser@yourdomain.com")]
        public string UserUatTest
        {
            get
            {
                return ((string)(this["UserUatTest"]));
            }
            set
            {
                this["UserUatTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yourPassword")]
        public string UserUatPassword
        {
            get
            {
                return ((string)(this["UserUatPassword"]));
            }
            set
            {
                this["UserUatPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://yourenvironment.crm4.dynamics.com/")]
        public string URLUat
        {
            get
            {
                return ((string)(this["URLUat"]));
            }
            set
            {
                this["URLUat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("youruser@yourdomain.com")]
        public string UserProTest
        {
            get
            {
                return ((string)(this["UserProTest"]));
            }
            set
            {
                this["UserProTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yourPassword")]
        public string UserProPassword
        {
            get
            {
                return ((string)(this["UserProPassword"]));
            }
            set
            {
                this["UserProPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://yourenvironment.crm4.dynamics.com/")]
        public string URLPro
        {
            get
            {
                return ((string)(this["URLPro"]));
            }
            set
            {
                this["URLPro"] = value;
            }
        }
    }
}
